top:
  LINE_SPACING: 1.1
  CONSOLE_FONT_SIZE: 12
  CONSOLE_LINE_SPACING: 1.0
  CONSOLE_FONT_NAME: Inconsolata-dz

font:
  EDITOR_FONT_NAME: Inconsolata-dz
  EDITOR_FONT_SIZE: 14
  
colors:
  ANNOTATIONS_COLOR: default
  ANNOTATIONS_MERGED_COLOR: default
  CARET_ROW_COLOR: highlight_bg
  GUTTER_BACKGROUND: background
  LINE_NUMBERS_COLOR: comment
  TEARLINE_COLOR: background
