top:
  LINE_SPACING: 1.1
  EDITOR_FONT_SIZE: 16
  CONSOLE_FONT_SIZE: 12
  CONSOLE_LINE_SPACING: 1.0
  EDITOR_FONT_NAME: Menlo
  
colors:
  ANNOTATIONS_COLOR: default
  ANNOTATIONS_MERGED_COLOR: default
  GUTTER_BACKGROUND: background
  LINE_NUMBERS_COLOR: comment
  TEARLINE_COLOR: background
